### ISSUE TITLE
Erro no comando python main.py

### ISSUE THREAD

**Issue by uchinaru** [marcellobatiista/KL-Bot#2]
Marcelo, boa tarde.

Apresentou erro ai iniciar o main, pode auxiliar ?

PS C:\Users\Algo Gamer\OneDrive\Área de Trabalho\KL-Bot> python main.py
Downloading...
From (uriginal): https://drive.google.com/uc?id=1AgCfsPPDVmrELV95R1mzgkZZA0Z2LKeX
From (redirected): https://drive.google.com/uc?id=1AgCfsPPDVmrELV95R1mzgkZZA0Z2LKeX&confirm=t&uuid=7263b096-9ce4-43df-9172-f8eab1a6ec3e
To: C:\Users\Algo Gamer\OneDrive\Área de Trabalho\KL-Bot\tesseract.rar
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 70.4M/70.4M [00:08<00:00, 8.33MB/s]

patool: Extracting tesseract.rar ...
Traceback (most recent call last):
  File "C:\Users\Algo Gamer\OneDrive\Área de Trabalho\KL-Bot\main.py", line 17, in <module>
    download_tesseract()
  File "C:\Users\Algo Gamer\OneDrive\Área de Trabalho\KL-Bot\system\downloads.py", line 29, in download_tesseract
    patoolib.extract_archive(output, outdir='comp_out/')
  File "C:\Users\Algo Gamer\AppData\Local\Programs\Python\Python310\lib\site-packages\patoolib\__init__.py", line 684, in extract_archive
    return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program)
  File "C:\Users\Algo Gamer\AppData\Local\Programs\Python\Python310\lib\site-packages\patoolib\__init__.py", line 470, in _extract_archive
    program = find_archive_program(format, 'extract', program=program)
  File "C:\Users\Algo Gamer\AppData\Local\Programs\Python\Python310\lib\site-packages\patoolib\__init__.py", line 336, in find_archive_program
    raise util.PatoolError("could not find an executable program to %s format %s; candidates are (%s)," % (command, format, ",".join(programs)))
patoolib.util.PatoolError: could not find an executable program to extract format rar; candidates are (rar,unrar,7z),

**Comment by marcellobatiista** [comment]
Olá. 
Não foi encontrado nenhum programa para extrair o arquivo .rar baixado.

1 - Instala os requerimentos: pip install -r requeriments.txt
2 - Executa o main.py

Se após instalar os requerimentos, não funcionar:

1 - Adicione a pasta do WinRar no Path, variáveis de ambiente do Windows.
2 - Executa o main.py

**Comment by talinatyros** [comment]
C:\Users\ghost>C:\Users\ghost\Desktop\KL-Bot-main\login.py
Traceback (most recent call last):
  File "C:\Users\ghost\Desktop\KL-Bot-main\login.py", line 8, in <module>
    from PyQt6.QtWidgets import QMainWindow, QApplication
ImportError: DLL load failed while importing QtWidgets: No se encontró el proceso especificado.

eu tenho errado nao funciona

**Comment by talinatyros** [comment]
C:\Users\ghost>C:\Users\ghost\Desktop\KL-Bot-main\main.py
Traceback (most recent call last):
  File "C:\Users\ghost\Desktop\KL-Bot-main\main.py", line 14, in <module>
    from PyQt6.QtWidgets import QMainWindow, QApplication
ImportError: DLL load failed while importing QtWidgets: No se encontró el proceso especificado.
